package com.gsm.controller;

import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

import javax.servlet.http.HttpServletRequest;

/**
 * Handles web requests related to user authentication, such as displaying the login page.
 */
@Controller
public class AuthController {

    /**
     * Displays the login page. It can also show error or logout messages.
     * @param error  A request parameter present if the last login attempt failed.
     * @param logout A request parameter present after a successful logout.
     * @param model  The Spring Model object to pass attributes to the view.
     * @param request The HttpServletRequest, used to access the CSRF token.
     * @return The name of the login view template.
     */
    @GetMapping("/login")
    public String loginPage(@RequestParam(value = "error", required = false) String error,
                            @RequestParam(value = "logout", required = false) String logout,
                            Model model,
                            HttpServletRequest request) {

        if (error != null) {
            model.addAttribute("errorMessage", "Invalid username or password.");
        }
        if (logout != null) {
            model.addAttribute("logoutMessage", "You have been logged out successfully.");
        }

        /**
         * IMPORTANT: Retrieves the CSRF token generated by Spring Security from the request
         * and adds it to the model. This makes the token available for use in the Thymeleaf/Mustache form.
         */
        model.addAttribute("_csrf", request.getAttribute(CsrfToken.class.getName()));

        return "login/login";
    }
}